# data download settings

[data.download_settings]
download_dir = "data"
skip_download = ["competition.competition_data", "competition.test_annot", "post_competition.original_train_noise_test", "post_competition.noise_data"] # put unwanted downloads here

[data.competition.competition_data]
url = "https://drive.google.com/drive/folders/1cZNgZ1Hq_19TbyH1EWbS2pRZElNIG3NG"

[data.competition.test_annot]
url = "https://drive.google.com/file/d/1dfb5wDx-AUzIJHRiyv7PxqDVkCONME4b"

[data.post_competition.original_train_noise_test]
url = "https://drive.google.com/drive/folders/1GAnGZZU5VCMmKxurdvk1RcarUVVz9AJh"

[data.post_competition.noise_data]
url = "https://drive.google.com/drive/folders/1Y5R0u67EnoRBCdFWtnt9a-V5CBzpg0VQ"


# predictions download settings

[predictions.download_settings]
download_dir = "predictions"
skip_download = ["post_competition_baselines"] # put unwanted downloads here

[predictions.competition_baselines]
url = "https://drive.google.com/file/d/1R9XZXa5FEcEKXxjdb2NHBRC21A4hGgMd"

[predictions.competition_submissions]
url = "https://drive.google.com/file/d/1MK-X-rNkVI0mNGBvAYtwCZQaM6NEngAn"

[predictions.rerun_top_submissions]
url = "https://drive.google.com/file/d/1c_7Ap7pl_WcOP1qnVhp7pWvDKhlmB8-W"

[predictions.best_of_top_submissions]
url = "https://drive.google.com/file/d/16aW6kMsLtOh1QcWxY279zAmVRbZgqIWb"


# scores download settings

[scores.download_settings]
download_dir = "scores"
skip_download = [] # put unwanted downloads here

[scores.best_of_top_submissions-finite]
url = "https://drive.google.com/file/d/1YwpPbs5kFSZpq70lOzs3NwVm628RPO-k"

[scores.competition_baselines-finite]
url = "https://drive.google.com/file/d/1M37bpn4ZBx7ObbozybOeRS0_zQe6OPwI"

[scores.competition_submissions-finite]
url = "https://drive.google.com/file/d/1u7mrlVbd-pb8FToglI85oJ6mVNKz3eY_"

[scores.rerun_top_submissions-finite]
url = "https://drive.google.com/file/d/10_IRyJ6YmXh7UlYdL8OSIlbbWKginu9n"