# data download settings

[data.download_settings]
download_dir = "data"
skip_download = ["competition.competition_data", "competition.test_annot", "post_competition.original_train_noise_test", "post_competition.noise_data"] # put unwanted downloads here

[data.competition.competition_data]
url = "https://drive.google.com/drive/folders/1cZNgZ1Hq_19TbyH1EWbS2pRZElNIG3NG"

[data.competition.test_annot]
url = "https://drive.google.com/file/d/1dfb5wDx-AUzIJHRiyv7PxqDVkCONME4b"

[data.post_competition.original_train_noise_test]
url = "https://drive.google.com/drive/folders/1GAnGZZU5VCMmKxurdvk1RcarUVVz9AJh"

[data.post_competition.noise_data]
url = "https://drive.google.com/drive/folders/1Y5R0u67EnoRBCdFWtnt9a-V5CBzpg0VQ"


# predictions download settings

[predictions.download_settings]
download_dir = "predictions"
skip_download = ["post_competition_baselines"] # put unwanted downloads here

[predictions.competition_baselines]
url = "https://drive.google.com/file/d/11sg07PEAyBqJPotFB4rGzq6usE9QOUg4"

[predictions.competition_submissions]
url = "https://drive.google.com/file/d/1MK-X-rNkVI0mNGBvAYtwCZQaM6NEngAn"

[predictions.post_competition_baselines]
url = ""

[predictions.rerun_top_submissions]
url = "https://drive.google.com/file/d/1psr4qrwz-2wjhswHLgThAqdQy_MhBaK4"

[predictions.best_of_top_submissions]
url = "https://drive.google.com/file/d/1yKrvvnxVPwk-VvO7_is-F1WeWeLt9Bcl"